apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    app: mynginx
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 200m
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 200Mi
      ports:
        - containerPort: 80
          name: http
