apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: "MYSQL_USER"
          value: "vanloc"
        - name: "MYSQL_PASSWORD"
          value: "123123"
        - name: "MYSQL_DATABASE"
          value: "microservice"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "root"
      ports:
        - containerPort: 3306
          name: http
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
  volumes:
    - name: mysql-volume
      hostPath:
        path: /microservice-data/mysql
  restartPolicy: Always