apiVersion: v1
kind: Pod
metadata:
  name: product-api
  labels:
    app: product-api
spec:
  containers:
    - name: product-api
      image: chauvanloc/product-api
      ports:
        - containerPort: 3002
          name: http
      envFrom:
        - configMapRef:
            name: env
        - configMapRef:
            name: env-elasticsearch
        - configMapRef:
            name: env-bullqueue
        - configMapRef:
            name: env-rabbitmq
        - configMapRef:
            name: env-product
  restartPolicy: Always
