apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq
    env:
    - name: "RABBITMQ_DEFAULT_USER"
      value: "vanloc"
    - name: "RABBITMQ_DEFAULT_PASS"
      value: "123123"
    ports:
    - containerPort: 5672
    - containerPort: 15672
    volumeMounts:
    - mountPath: /var/lib/rabbitmq
      name: rabbitmq-volume
  volumes:
  - name: rabbitmq-volume
    hostPath:
      path: /microservice-data
