apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-api
  type: ClusterIP
  ports:
  - name: user-service
    protocol: TCP
    port: 31000
    targetPort: 31000