Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "172.16.10.104"
  config.vm.hostname = "worker4.xtl"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "worker4.xtl"
     vb.cpus = 2
     vb.memory = "2048"
  end
end