Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "172.16.10.101"
  config.vm.hostname = "worker1.xtl"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "worker1.xtl"
     vb.cpus = 2
     vb.memory = "2048"
  end
end